### ISSUE TITLE
Poisson surface reconstruction

### ISSUE THREAD

**Issue by IdeVdB** [davecasp/flowssm#2]
I am not able to find in the code where the Poisson surface reconstruction happens after learning the hub representations to generate the template. Could it be that this is not implemented in the generate_template.py file?

Thank you already!

**Comment by davecasp** [comment]
Thanks for the interest in the project. 

For the poisson surface reconstruction we leveraged MeshLab (https://www.meshlab.net) and their interactive unscreened Poisson surface reconstruction, which can be found under filters. 

If you have any more questions please let me know.
