### ISSUE TITLE
Questions regarding template generation and training

### ISSUE THREAD

**Issue by iyerkrithika21** [davecasp/flowssm#3]
1. In the data description, you mention: 
```Shapes are to be in .ply format and organised into train, val and test directories, with a mean.ply template.```
How should the `mean.ply` be created? The `generate_template.sh` only non-rigidly aligned training shapes and creates meshes with the same number of vertices and faces (saves each mesh a `.obj`  file in the run folder) and does not generate the mean.ply template mesh?

2. Could you please clarify how `generate_template.sh` and `train.sh` should be used? 
https://github.com/davecasp/flowssm/blob/7befa4eb49665fe336005a73a92dc65d82227a28/train.sh#L8
Should the data folder point to the template folder or the original data? Where should the mean.ply be saved?

**Comment by davecasp** [comment]
1. _As a short disclaimer in the beginning:_ generating a template shape was not the focus of our work. Thus, the applied template generation is just one possible solution to find a good template. 
The generate_template.sh only does the non-rigid alignment using shapeflow. From the aligned shapes we have generated a template using a unscreened poisson surface reconstruction as explained in #2 followed by a mesh simplification to reduce the number of faces.

2. The data_root should point to a folder that includes the folders `'train'/'val'/'test'`, which include the `mean.ply` and other train/val/test shapes `*.ply`. (Note: Depending on the variance of alignment of the shapes it could be helpful to align your shapes to the template using a rigid ICP.) The details to the data loading can be found here in:
https://github.com/davecasp/flowssm/blob/7befa4eb49665fe336005a73a92dc65d82227a28/utils/dataloader.py#L155-L162
https://github.com/davecasp/flowssm/blob/7befa4eb49665fe336005a73a92dc65d82227a28/utils/dataloader.py#L786-L791
