### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by NarSB** [davecasp/flowssm#4]
Dear flowssm developers,

We want to test your libary for research purposes. We have successfuly installed the library. We are blocked in Data section. We have not found any dataset example or more information of how to proceed to our own one. 
Please, do you have a dataset with the required structure? 

Best regards,
Narcís Sayols.

**Comment by davecasp** [comment]
Dear Narcis Sayols,

as described in the README you can use any publicly available triangulated surface mesh dataset as long as you provide them in `.ply` format and organize them into "train", "val", and "test" directories, with a `mean.ply` template. For further details please consider our answer to #3.

Hope this answers your questions!
Best regards
David
